"""Curated seed library of "Dog Fact of the Day" entries.

Hand-picked so the voice stays warm + accurate. Tags keep the rotation
varied. Each entry: {text, tag, emoji}. The DB id is generated at seed time.

Aim: enough facts that the daily rotation stays fresh for ~6 months before
anything repeats. Operator can add their own via the admin UI.
"""
from typing import List, Dict

DOG_FACTS_SEED: List[Dict[str, str]] = [
    # ── Anatomy / biology ────────────────────────────────────────────
    {"text": "A dog's sense of smell is roughly 10,000 to 100,000 times more sensitive than a human's.", "tag": "anatomy", "emoji": "👃"},
    {"text": "Dogs have three eyelids — the third one is called the haw and helps keep the eye moist.", "tag": "anatomy", "emoji": "👁️"},
    {"text": "Every dog's nose print is unique — like a human's fingerprint.", "tag": "anatomy", "emoji": "🐾"},
    {"text": "Dogs can hear sounds up to four times farther away than humans, and at frequencies we can't.", "tag": "anatomy", "emoji": "👂"},
    {"text": "Most dogs have 42 adult teeth — 10 more than humans.", "tag": "anatomy", "emoji": "🦷"},
    {"text": "Dogs sweat through their paw pads — not their skin. Panting does most of the cooling.", "tag": "anatomy", "emoji": "💧"},
    {"text": "A dog's normal body temperature is about 101–102.5°F (38.3–39.2°C) — warmer than ours.", "tag": "anatomy", "emoji": "🌡️"},
    {"text": "Dogs have eighteen muscles controlling each ear — that's why they're so expressive.", "tag": "anatomy", "emoji": "👂"},
    {"text": "A dog's whiskers can detect tiny changes in air currents around them.", "tag": "anatomy", "emoji": "✨"},
    {"text": "Puppies are born blind and deaf. Their eyes open around 10–14 days, hearing follows shortly after.", "tag": "anatomy", "emoji": "🐶"},
    {"text": "Dogs see best in low light — their tapetum lucidum is the same thing that makes cats' eyes glow.", "tag": "anatomy", "emoji": "🌙"},
    {"text": "Greyhounds have the largest hearts (relative to body size) of any dog breed.", "tag": "anatomy", "emoji": "❤️"},
    {"text": "Dogs are not colorblind — they see blues and yellows, just not reds and greens the way we do.", "tag": "myth-buster", "emoji": "🌈"},
    {"text": "A dog's heart beats between 70 and 120 times a minute at rest, faster in small breeds.", "tag": "anatomy", "emoji": "💗"},
    {"text": "Dogs have a special organ called the Jacobson's organ that lets them \"taste\" smells.", "tag": "anatomy", "emoji": "👃"},
    # ── Behavior ─────────────────────────────────────────────────────
    {"text": "When dogs sleep curled in a ball, it's an instinct from their wild ancestors protecting vital organs and conserving heat.", "tag": "behavior", "emoji": "💤"},
    {"text": "Tail-wagging direction matters — right-side wags often mean happy, left-side wags mean unsure.", "tag": "behavior", "emoji": "🦴"},
    {"text": "Dogs dream — REM sleep activity in their brains looks remarkably similar to ours.", "tag": "behavior", "emoji": "💭"},
    {"text": "A dog's \"play bow\" (front down, butt up) is an invitation that means \"I'm only playing, no fight.\"", "tag": "behavior", "emoji": "🎾"},
    {"text": "Dogs yawn when they're stressed, not just sleepy — it's a calming signal.", "tag": "behavior", "emoji": "🥱"},
    {"text": "Licking is how dogs greet, show affection, and learn — puppies lick their mom to get fed.", "tag": "behavior", "emoji": "👅"},
    {"text": "Most dogs are right-pawed or left-pawed, just like humans favor a hand.", "tag": "behavior", "emoji": "🐾"},
    {"text": "Dogs roll in stinky stuff to mask their own scent — an ancient hunting instinct.", "tag": "behavior", "emoji": "🌿"},
    {"text": "When your dog brings you a toy, they're sharing — it's the highest compliment in dog language.", "tag": "behavior", "emoji": "🧸"},
    {"text": "Dogs that lean against you aren't being needy — they're showing trust and seeking comfort.", "tag": "behavior", "emoji": "🤗"},
    {"text": "The \"zoomies\" (FRAP — Frenetic Random Activity Periods) are a normal release of pent-up energy.", "tag": "behavior", "emoji": "💨"},
    {"text": "Dogs tilt their heads to better locate where a sound is coming from — and to read your face.", "tag": "behavior", "emoji": "🤔"},
    {"text": "Howling is contagious — one starts, others join. It's a pack-bonding behavior left over from wolves.", "tag": "behavior", "emoji": "🐺"},
    {"text": "Dogs see eye contact as either bonding (with people they trust) or as a challenge (from strangers).", "tag": "behavior", "emoji": "👀"},
    {"text": "When a dog yawns after you yawn, that's empathy — dogs literally catch yawns from their humans.", "tag": "behavior", "emoji": "🥱"},
    {"text": "Dogs kick after they poop to mark territory with scent glands in their paws — not to bury it.", "tag": "myth-buster", "emoji": "🐾"},
    {"text": "A wagging tail doesn't always mean a happy dog — slow stiff wags can signal a warning.", "tag": "myth-buster", "emoji": "⚠️"},
    {"text": "Dogs greet by sniffing each other's backsides because anal glands carry a chemical \"ID badge.\"", "tag": "behavior", "emoji": "🐾"},
    {"text": "Puppy chewing isn't bad behavior — it's how they explore their world (and soothe teething).", "tag": "behavior", "emoji": "🦴"},
    {"text": "Dogs can read human emotions from facial expressions, even in photographs.", "tag": "behavior", "emoji": "😊"},
    # ── Health / care ────────────────────────────────────────────────
    {"text": "Chocolate is toxic to dogs because they metabolize theobromine much more slowly than humans do.", "tag": "health", "emoji": "🍫"},
    {"text": "Grapes and raisins can cause kidney failure in dogs — even just a few.", "tag": "health", "emoji": "🍇"},
    {"text": "Xylitol (a sweetener in sugar-free gum and peanut butter) is deadly to dogs — always check labels.", "tag": "health", "emoji": "⚠️"},
    {"text": "A dog's ideal weight check: you should feel ribs easily but not see them clearly.", "tag": "health", "emoji": "⚖️"},
    {"text": "Dogs should brush their teeth too — daily ideally. Dental disease is the #1 health issue in adult dogs.", "tag": "health", "emoji": "🪥"},
    {"text": "Dogs can suffer from heatstroke at 85°F (29°C) — pavement temperature matters more than air temp.", "tag": "health", "emoji": "🌡️"},
    {"text": "Onions, garlic, and chives are all toxic to dogs — even in small amounts over time.", "tag": "health", "emoji": "🧅"},
    {"text": "Spayed/neutered dogs typically live 1–3 years longer than intact dogs.", "tag": "health", "emoji": "🩺"},
    {"text": "A dog's lifespan correlates inversely with size — small breeds often live 12–16 years, giants 6–10.", "tag": "health", "emoji": "📏"},
    {"text": "Yearly dental cleanings can add years to a dog's life — tooth bacteria reach the heart and kidneys.", "tag": "health", "emoji": "🦷"},
    {"text": "Most dogs need 12–14 hours of sleep a day. Puppies and seniors can hit 18+ hours.", "tag": "health", "emoji": "💤"},
    {"text": "Tap water is fine for most dogs — but if you wouldn't drink it, neither should they.", "tag": "health", "emoji": "💧"},
    {"text": "Dogs should never ride in the back of an open pickup truck — leading cause of preventable injuries.", "tag": "health", "emoji": "🚗"},
    {"text": "If a dog vomits more than twice in 12 hours, or won't drink water, call your vet — don't wait.", "tag": "health", "emoji": "🩺"},
    {"text": "Walking on hot pavement: if you can't hold the back of your hand on it for 7 seconds, it's too hot for paws.", "tag": "health", "emoji": "🔥"},
    # ── Breeds ───────────────────────────────────────────────────────
    {"text": "Labrador Retrievers have been the most popular breed in the U.S. for 31 consecutive years (until 2022).", "tag": "breed", "emoji": "🥇"},
    {"text": "Dalmatians are born pure white — their spots develop over the first weeks of life.", "tag": "breed", "emoji": "⚫"},
    {"text": "Basenjis don't bark — they yodel (the \"baroo\" sound).", "tag": "breed", "emoji": "🎶"},
    {"text": "Chow Chows and Shar-Peis are the only two breeds with blue-black tongues.", "tag": "breed", "emoji": "👅"},
    {"text": "The Saluki, Afghan Hound, and Pharaoh Hound are some of the oldest known breeds — over 5,000 years old.", "tag": "breed", "emoji": "🏛️"},
    {"text": "Newfoundlands have webbed feet — they were bred to rescue people from cold water.", "tag": "breed", "emoji": "🌊"},
    {"text": "Border Collies are widely regarded as the smartest breed — they can learn 1,000+ words.", "tag": "breed", "emoji": "🧠"},
    {"text": "Beagles have the second-best sense of smell (after Bloodhounds) and are used at airports.", "tag": "breed", "emoji": "👃"},
    {"text": "The Cane Corso's name roughly translates to \"bodyguard dog\" in Latin.", "tag": "breed", "emoji": "🛡️"},
    {"text": "Pugs were bred as companions for Chinese emperors — their wrinkled foreheads were said to resemble the character for \"prince.\"", "tag": "breed", "emoji": "👑"},
    {"text": "Greyhounds can hit 45 mph — they're the fastest dog breed.", "tag": "breed", "emoji": "💨"},
    {"text": "Bloodhounds' tracking results have been used as legal evidence in court for over 100 years.", "tag": "breed", "emoji": "🔎"},
    {"text": "Poodles came from Germany, not France — \"Pudel\" means \"to splash\" (water retrievers).", "tag": "breed", "emoji": "💦"},
    {"text": "The Norwegian Lundehund has six toes on each paw and can bend its head backward.", "tag": "breed", "emoji": "🦶"},
    {"text": "Saint Bernards do not actually carry brandy barrels — that's a myth from a single Victorian painting.", "tag": "myth-buster", "emoji": "🍷"},
    {"text": "Yorkshire Terriers were originally bred to catch rats in 19th-century English textile mills.", "tag": "breed", "emoji": "🏭"},
    {"text": "The smallest dog breed is the Chihuahua; the tallest is the Irish Wolfhound.", "tag": "breed", "emoji": "📏"},
    {"text": "Akitas were once reserved for Japanese royalty — gifting a small statue means wishing good health.", "tag": "breed", "emoji": "🎌"},
    # ── Fun / heart-warmers ─────────────────────────────────────────
    {"text": "A dog's average attention span on a single task is about 20 seconds — train in short bursts.", "tag": "fun", "emoji": "⏱️"},
    {"text": "The oldest dog on record lived to 31 — Bobi, a Portuguese Rafeiro do Alentejo.", "tag": "fun", "emoji": "🎂"},
    {"text": "Three dogs survived the sinking of the Titanic — all small breeds carried by first-class passengers.", "tag": "fun", "emoji": "🚢"},
    {"text": "Laika was the first living being to orbit Earth — she launched aboard Sputnik 2 in 1957.", "tag": "fun", "emoji": "🚀"},
    {"text": "There are over 340 recognized dog breeds in the world.", "tag": "fun", "emoji": "🐕"},
    {"text": "The Beatles song \"A Day in the Life\" contains an ultrasonic whistle audible only to dogs.", "tag": "fun", "emoji": "🎵"},
    {"text": "Bingo was the name of the dog in the classic children's song — but \"B-I-N-G-O\" refers to the farmer, not the dog. (The dog is unnamed!)", "tag": "fun", "emoji": "🎵"},
    {"text": "A dog's stomach can rotate or twist on itself (bloat) — large deep-chested breeds are especially at risk.", "tag": "health", "emoji": "⚠️"},
    {"text": "The Russian word for \"hello\" sounds enough like \"sit\" that some Russian dog trainers use different words to avoid confusion.", "tag": "fun", "emoji": "🌍"},
    {"text": "Petting a dog measurably lowers human blood pressure — and the dog's, too.", "tag": "fun", "emoji": "💕"},
    {"text": "Service dogs can sense an oncoming seizure 15–45 minutes before it happens.", "tag": "fun", "emoji": "🩺"},
    {"text": "A study found dogs can detect cancer cells through scent with up to 97% accuracy.", "tag": "fun", "emoji": "🔬"},
    {"text": "The phrase \"dog days of summer\" comes from Sirius (the Dog Star) — not from dogs at all.", "tag": "fun", "emoji": "⭐"},
    {"text": "Dogs were the first animal humans ever domesticated — possibly 15,000 to 40,000 years ago.", "tag": "fun", "emoji": "🦴"},
    {"text": "More than 75 million dogs live in the United States — more than any other country.", "tag": "fun", "emoji": "🇺🇸"},
    {"text": "There's a beach in Carmel, California where dogs aren't just allowed — they're celebrated. Carmel Beach is famously off-leash.", "tag": "fun", "emoji": "🏖️"},
    {"text": "The most-watched dog show on television is the Westminster Kennel Club, broadcast since 1948.", "tag": "fun", "emoji": "📺"},
    {"text": "The word \"puppy\" comes from the French \"poupée,\" meaning doll.", "tag": "fun", "emoji": "🎀"},
    {"text": "Dogs were trained as paratroopers in WWII — over 30,000 served in various canine units.", "tag": "fun", "emoji": "🪂"},
    {"text": "The dog from \"The Wizard of Oz\" (Toto) was a female Cairn Terrier named Terry.", "tag": "fun", "emoji": "🌪️"},
    # ── Training ─────────────────────────────────────────────────────
    {"text": "Positive reinforcement (rewarding what you want) is far more effective than punishing what you don't.", "tag": "training", "emoji": "🦴"},
    {"text": "Five minutes of training 3x a day beats one 30-minute session — dogs learn best in short bursts.", "tag": "training", "emoji": "⏱️"},
    {"text": "Use the same word for a command — \"down\" and \"lie down\" sound different to a dog.", "tag": "training", "emoji": "🐶"},
    {"text": "Dogs respond to tone of voice more than the actual words you say.", "tag": "training", "emoji": "🗣️"},
    {"text": "Treats work best when they're small (pea-sized) and saved for training, not free snacking.", "tag": "training", "emoji": "🥓"},
    {"text": "Clicker training is so effective because the click marks the exact instant the dog did the right thing.", "tag": "training", "emoji": "🔔"},
    {"text": "Socialization windows close around 16 weeks — puppies who haven't met the world by then need extra care later.", "tag": "training", "emoji": "👶"},
    {"text": "If you call your dog and they don't come, never punish them when they finally do — they'll learn to avoid coming.", "tag": "training", "emoji": "🏃"},
    {"text": "Leash pulling is best fixed by stopping when the leash gets tight — the dog learns that pulling = no progress.", "tag": "training", "emoji": "🦮"},
    {"text": "Crate training works because dogs are den animals — a properly introduced crate becomes a safe space, not a punishment.", "tag": "training", "emoji": "🏠"},
    {"text": "Counter-surfing is fixed by never letting a dog \"win\" food on the counter — even once builds the habit.", "tag": "training", "emoji": "🍽️"},
    {"text": "A tired dog is a well-behaved dog. Most behavior problems trace back to under-exercise.", "tag": "training", "emoji": "🎾"},
    {"text": "Old dogs absolutely can learn new tricks — they may take more reps, but they're often calmer learners.", "tag": "myth-buster", "emoji": "🐕"},
    {"text": "Dominance training is outdated science — modern force-free methods are more effective and humane.", "tag": "myth-buster", "emoji": "📚"},
    {"text": "Nose work (scent games) tires a dog more than a long walk — 10 minutes of sniffing = an hour of walking.", "tag": "training", "emoji": "👃"},
    # ── More breeds for variety ──────────────────────────────────────
    {"text": "The Australian Shepherd was actually developed in the United States, despite its name.", "tag": "breed", "emoji": "🇺🇸"},
    {"text": "Boxers got their name from their tendency to stand on their back legs and \"box\" with their front paws when playing.", "tag": "breed", "emoji": "🥊"},
    {"text": "Dachshunds (\"badger dogs\") were originally bred to crawl into badger dens — that's why they're so long and low.", "tag": "breed", "emoji": "🦡"},
    {"text": "Bernese Mountain Dogs were bred to drive cattle and pull carts in the Swiss Alps.", "tag": "breed", "emoji": "⛰️"},
    {"text": "The Pembroke Welsh Corgi was Queen Elizabeth II's favorite breed — she owned over 30 in her lifetime.", "tag": "breed", "emoji": "👑"},
    {"text": "The Doberman Pinscher was developed by a German tax collector who wanted a guard dog for his rounds.", "tag": "breed", "emoji": "💼"},
    {"text": "Australian Cattle Dogs are also called \"Blue Heelers\" because they nip cattle at the heels to move them.", "tag": "breed", "emoji": "🐄"},
    {"text": "Whippets are essentially miniature Greyhounds — they hit 35 mph and were nicknamed \"the poor man's racehorse.\"", "tag": "breed", "emoji": "💨"},
    {"text": "The Tibetan Mastiff was bred to guard monasteries in the Himalayas — and is one of the largest breeds alive.", "tag": "breed", "emoji": "🏔️"},
    {"text": "Vizslas are nicknamed \"velcro dogs\" because they form intense bonds with one person and follow them everywhere.", "tag": "breed", "emoji": "💕"},
    {"text": "The Catahoula Leopard Dog is Louisiana's state dog and is known for its often-piercing pale blue \"glass eyes.\"", "tag": "breed", "emoji": "👁️"},
    {"text": "Komondors look like mops because their corded white coat helps them blend in with sheep flocks they guard.", "tag": "breed", "emoji": "🐑"},
    {"text": "The Pharaoh Hound's ears and nose actually blush when it's happy or excited.", "tag": "breed", "emoji": "☺️"},
    {"text": "Bichon Frise means \"curly lap dog\" in French — they were trade currency on Spanish ships in the 1300s.", "tag": "breed", "emoji": "⛵"},
    {"text": "The Black-and-Tan Coonhound was developed in Appalachia to tree raccoons by scent alone.", "tag": "breed", "emoji": "🦝"},
    # ── More health ──────────────────────────────────────────────────
    {"text": "Senior dogs (7+ in most breeds) benefit from twice-yearly vet checks, not once a year.", "tag": "health", "emoji": "🩺"},
    {"text": "Mushrooms growing wild in your yard can be lethal to a curious dog — remove them on sight.", "tag": "health", "emoji": "🍄"},
    {"text": "Macadamia nuts cause weakness and tremors in dogs even at small doses.", "tag": "health", "emoji": "🥜"},
    {"text": "Antifreeze tastes sweet to dogs and is fatal in tiny amounts — clean any spills immediately.", "tag": "health", "emoji": "⚠️"},
    {"text": "A normal heart rate for a healthy dog at rest: small breeds 100–140 bpm, large breeds 60–100 bpm.", "tag": "health", "emoji": "💓"},
    {"text": "Heartworm prevention is year-round in most U.S. states — mosquitoes survive longer than we think.", "tag": "health", "emoji": "🦟"},
    {"text": "Dogs need joint care from age 5+ — even active dogs can develop arthritis silently.", "tag": "health", "emoji": "🦴"},
    {"text": "Salt-water beach dogs need fresh water available every 30 minutes — saltwater poisoning is real.", "tag": "health", "emoji": "🌊"},
    {"text": "Hot cars hit 120°F (49°C) in under 20 minutes, even with windows cracked — never leave dogs in cars.", "tag": "health", "emoji": "🚗"},
    {"text": "Dogs with light/pink skin and short coats can get sunburned — especially on noses and bellies.", "tag": "health", "emoji": "☀️"},
    {"text": "Tick checks should happen after EVERY outdoor adventure, especially behind ears and between toes.", "tag": "health", "emoji": "🔍"},
    {"text": "A dog drinking suddenly more water than usual is the #1 early sign of kidney or diabetes problems — call your vet.", "tag": "health", "emoji": "💧"},
    {"text": "Probiotics specifically for dogs (not human ones) can help digestion, especially after antibiotics.", "tag": "health", "emoji": "🦠"},
    {"text": "Cherry tomatoes are okay in tiny amounts; the green leaves and stems of tomato plants are toxic.", "tag": "health", "emoji": "🍅"},
    {"text": "A dog's tongue isn't actually self-cleaning — bad breath usually means dental disease, not just \"dog smell.\"", "tag": "myth-buster", "emoji": "🐕"},
    # ── More fun / culture ──────────────────────────────────────────
    {"text": "Snoop Dogg actually owns three real-life dogs — all rescued.", "tag": "fun", "emoji": "🎤"},
    {"text": "The phrase \"raining cats and dogs\" likely comes from medieval thatched roofs where animals sheltered — and got washed out in storms.", "tag": "fun", "emoji": "🌧️"},
    {"text": "Dogs have starred in movies for over a century — the first canine film star was a Border Collie named Blair, in 1905.", "tag": "fun", "emoji": "🎬"},
    {"text": "There's a Buddhist temple in Japan dedicated entirely to dogs — visitors leave bowls of food and toys.", "tag": "fun", "emoji": "⛩️"},
    {"text": "In Switzerland, it's illegal to own only one social dog like a Bernese — they're considered \"social animals\" by law.", "tag": "fun", "emoji": "🇨🇭"},
    {"text": "The first dog to be inducted into the Animal Hall of Fame was Balto, a Siberian Husky who led a serum run to Nome in 1925.", "tag": "fun", "emoji": "🏅"},
    {"text": "There's a city in Spain — Sant Joan de les Abadesses — where a dog named Pippo was elected to municipal office.", "tag": "fun", "emoji": "🗳️"},
    {"text": "A Beagle named Buddy was the first known dog to be infected with COVID-19 — he recovered fully.", "tag": "fun", "emoji": "🐕"},
    {"text": "The world's most-watched livestream of all time is Norway's Slow TV broadcast featuring sheepdogs herding sheep in real-time.", "tag": "fun", "emoji": "📺"},
    {"text": "Bingo, Pluto, Snoopy, Lassie, Rex, Rover — for over a century, these have been the most-used dog names in fiction.", "tag": "fun", "emoji": "📚"},
    {"text": "A dog's life expectancy was just 7 years in 1900. Today, with vet care + nutrition, it's 11–13 years on average.", "tag": "fun", "emoji": "📈"},
    {"text": "There's a dog mayor in Idyllwild, California — Maximus Mighty-Dog Mueller III, a Golden Retriever, took office in 2014.", "tag": "fun", "emoji": "🏛️"},
    {"text": "The longest tongue on a dog measured 7.3 inches (18.58 cm) — held by a Saint Bernard named Mochi.", "tag": "fun", "emoji": "👅"},
    {"text": "The most expensive dog ever sold was a Tibetan Mastiff in 2014, for $1.9 million in China.", "tag": "fun", "emoji": "💰"},
    {"text": "A blind golden retriever named Endal was awarded an animal lifetime achievement award for his service work.", "tag": "fun", "emoji": "🏆"},
    {"text": "If your dog yawns when you yawn, that's empathy — dogs literally \"catch\" their owners' yawns.", "tag": "behavior", "emoji": "🥱"},
    {"text": "There are over 400 million dogs in the world. About half are pets, the rest are working or feral.", "tag": "fun", "emoji": "🌍"},
    {"text": "Hiking with your dog burns ~150 calories more per hour for them than walking on flat pavement.", "tag": "fun", "emoji": "🏔️"},
    {"text": "Dogs benefit from \"sniffaris\" — slow walks where they get to sniff freely. It's mental enrichment, not laziness.", "tag": "training", "emoji": "🌿"},
    {"text": "A wet dog can shake 70% of the water off its body in just four seconds.", "tag": "anatomy", "emoji": "💦"},
    {"text": "Dogs greet humans by sniffing because they get more information from one sniff than we do from looking.", "tag": "behavior", "emoji": "👃"},
    {"text": "Dog DNA tests are 99% accurate at breed identification — and increasingly accurate for health markers too.", "tag": "fun", "emoji": "🧬"},
    {"text": "Bringing home a new dog often takes 3–3–3 to settle: 3 days decompressing, 3 weeks learning routine, 3 months feeling at home.", "tag": "training", "emoji": "🏡"},
    {"text": "Dogs benefit hugely from puzzle feeders — they slow down eating and provide mental stimulation.", "tag": "training", "emoji": "🧩"},
    {"text": "A dog's bark can hit 100 decibels — louder than a chainsaw at close range.", "tag": "anatomy", "emoji": "📢"},
    {"text": "Adopting an older dog often means skipping the destructive puppy phase entirely — and they're just as bonded.", "tag": "fun", "emoji": "❤️"},
    {"text": "Dogs grieve. They often lose appetite or get clingy when a household pet or person dies.", "tag": "behavior", "emoji": "💔"},
    {"text": "Studies show dogs prefer cooler areas to sleep — hot floors and warm beds aren't actually their favorite.", "tag": "behavior", "emoji": "❄️"},
    {"text": "Dogs were used by Roman armies as war messengers, carrying sealed letters across enemy lines.", "tag": "fun", "emoji": "⚔️"},
    {"text": "A guide dog's harness is specially designed so the human can feel even tiny movements through the handle.", "tag": "fun", "emoji": "🦮"},
    {"text": "The most dogs ever walked at once: 22, by one person, in Australia in 2017.", "tag": "fun", "emoji": "🦮"},
    {"text": "An Australian Cattle Dog named Bluey lived to 29 — the longest verified lifespan for any dog until Bobi broke the record in 2023.", "tag": "fun", "emoji": "🎂"},
    {"text": "Dogs were once used to turn cooking spits in 16th-century kitchens — a breed called the Turnspit Dog.", "tag": "fun", "emoji": "🍗"},
    {"text": "There's a dog cafe in Tokyo where you can drink coffee surrounded by 30+ rescue dogs — proceeds fund adoptions.", "tag": "fun", "emoji": "☕"},
    {"text": "Two-thirds of dogs prefer to face north or south when they poop — scientists think it's related to Earth's magnetic field.", "tag": "fun", "emoji": "🧭"},
    {"text": "A dog's sense of time isn't great — but they can definitely tell the difference between an hour and a workday.", "tag": "behavior", "emoji": "⏰"},
    {"text": "Dogs that get regular off-leash time in safe areas tend to be more confident, less reactive on leash.", "tag": "training", "emoji": "🌳"},
    {"text": "A dog's nose secretes a thin mucus to capture scent molecules — wet noses smell better.", "tag": "anatomy", "emoji": "💧"},
    {"text": "There are around 100 \"command words\" the average pet dog will learn in their lifetime — overachievers learn 200+.", "tag": "fun", "emoji": "🗣️"},
    {"text": "Dogs prefer to greet new dogs by approaching curved, not head-on. Head-on can read as a challenge.", "tag": "behavior", "emoji": "🐾"},
    {"text": "Studies suggest dogs experience joy, fear, anger, disgust, and love — but not guilt. The \"guilty look\" is just appeasement.", "tag": "myth-buster", "emoji": "🐶"},
    {"text": "Some dogs (~10%) genuinely smile — lifting their lips in response to human affection. It's been observed across breeds.", "tag": "fun", "emoji": "😄"},
    {"text": "The world's loudest dog bark on record: 113.1 decibels, by a Golden Retriever named Charlie in Australia.", "tag": "fun", "emoji": "📢"},
    {"text": "Dogs were the first non-human soldiers awarded medals — the Dickin Medal has been given to military dogs since 1943.", "tag": "fun", "emoji": "🏅"},
    {"text": "Cats outsold dogs as pets in the U.S. once — for about 6 months in 2002. Dogs have led ever since.", "tag": "fun", "emoji": "📊"},
    {"text": "If a dog circles before lying down, it's an old wolf instinct — flattening grass and checking for snakes.", "tag": "behavior", "emoji": "🌀"},
    {"text": "Some dog breeds were specifically developed to hunt water rats, including the Standard Poodle.", "tag": "breed", "emoji": "🐀"},
    {"text": "A dog wagging only the tip of its tail (not the whole tail) often signals uncertainty or mild stress.", "tag": "behavior", "emoji": "🚦"},
    {"text": "There's a breed called the Mudi (Hungarian) that was only officially recognized by the AKC in 2022.", "tag": "breed", "emoji": "🇭🇺"},
    {"text": "Dogs can be allergic to humans — typically to dander or saliva. It's rare but documented.", "tag": "fun", "emoji": "🤧"},
    {"text": "The Old English Sheepdog has hair so thick it can sometimes hide a built-in pocket near the chin.", "tag": "breed", "emoji": "🐑"},
    {"text": "A 2019 study found dogs make eye contact more readily with their owners than with strangers — a sign of deep bonding.", "tag": "behavior", "emoji": "👀"},
    {"text": "Dogs can detect changes in human blood sugar — and trained diabetic alert dogs save lives daily.", "tag": "fun", "emoji": "🩸"},
    {"text": "Most dogs prefer their food slightly warm — body temperature mimics fresh-killed prey.", "tag": "fun", "emoji": "🍽️"},
    {"text": "There's a sport called \"Dock Diving\" where dogs leap from a dock chasing a toy — current world record is over 36 feet.", "tag": "fun", "emoji": "🌊"},
    {"text": "A 2-year-old Border Collie named Chaser learned the names of over 1,000 different toys and could fetch them by name.", "tag": "fun", "emoji": "🧠"},
    {"text": "Dogs use their right nostril to sniff new or threatening smells, and their left for familiar ones.", "tag": "anatomy", "emoji": "👃"},
    {"text": "Frozen Kongs (filled with peanut butter or pumpkin) make excellent crate-time treats — they last 20–30 minutes.", "tag": "training", "emoji": "❄️"},
    {"text": "Brushing your dog's coat distributes natural oils and keeps the skin healthy — even short-haired dogs benefit weekly.", "tag": "health", "emoji": "🪥"},
    {"text": "Dogs see TV — but most flat-screens flicker too slow for them. Modern 4K screens at 120Hz actually look smoother to dogs.", "tag": "fun", "emoji": "📺"},
    {"text": "A dog's hearing range is roughly 67 Hz to 45,000 Hz — humans top out around 20,000 Hz.", "tag": "anatomy", "emoji": "🔊"},
    {"text": "Some dogs naturally hate certain shapes — usually broomsticks, vacuums, or umbrellas. Often it's about sudden movement or noise.", "tag": "behavior", "emoji": "🧹"},
    {"text": "Dogs' brains shrink with age, just like humans — but mental enrichment slows the decline.", "tag": "health", "emoji": "🧠"},
    {"text": "There's a strain of yeast that lives naturally on dog paws — those \"corn chip\" smelling feet? That's it.", "tag": "fun", "emoji": "🌽"},
    {"text": "Dogs can learn the meaning of human pointing gestures — even wolves raised by humans don't do this naturally.", "tag": "fun", "emoji": "👉"},
    {"text": "A dog's bond with its human is biochemically the same as a parent-child bond — oxytocin levels rise on both sides.", "tag": "fun", "emoji": "❤️"},
]
