"""Registry of every transactional email Sit Happens sends.

This is the single source of truth for customizable email templates. Each
entry declares:
  - slug:        Stable machine ID used in the `email_templates` collection.
  - name:        Human label shown in Settings.
  - description: One-line explanation of when it fires.
  - category:    Bucket for grouping in the UI ("client", "admin").
  - audience:    "client" → owners; "admin" → operator/trainer.
  - default_subject / default_title / default_intro_html:
                 Hardcoded fallbacks used when no override row exists.
  - variables:   Available `{{var}}` placeholders the editor exposes as chips.

Email behavior is unchanged when no override row exists — the defaults
mirror the strings previously inlined in `email_service.py`.
"""

EMAIL_TEMPLATES = [
    # ---------------- Client-facing ----------------
    {
        "slug": "client_homework_assigned",
        "name": "Homework Assigned",
        "description": "Sent to the client when their dog gets a new homework plan.",
        "category": "client",
        "audience": "client",
        "default_subject": "New homework · {{homework_title}} · {{dog_name}}",
        "default_title": "📚 New homework · {{dog_name}}",
        "default_intro_html": "Hi {{first_name}}, your trainer just assigned <strong>{{homework_title}}</strong> for <strong>{{dog_name}}</strong>. Log in to your portal to start tracking sessions.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "dog_name", "homework_title", "due_date", "assigned_by"],
    },
    {
        "slug": "client_booking_approved",
        "name": "Booking Approved",
        "description": "Sent to the client when their requested booking is approved.",
        "category": "client",
        "audience": "client",
        "default_subject": "Booking confirmed · {{dog_name}} · {{date_range}}",
        "default_title": "✅ Booking confirmed",
        "default_intro_html": "Great news {{first_name}} — <strong>{{dog_name}}</strong>'s {{service_label}} booking for <strong>{{date_range}}</strong> is approved. See you soon!",
        "default_cta_text": "View Booking",
        "variables": ["first_name", "client_name", "dog_name", "service_label", "date_range", "kennel"],
    },
    {
        "slug": "client_certificate_issued",
        "name": "Certificate of Completion",
        "description": "Sent when a dog completes a homework program and a certificate is issued.",
        "category": "client",
        "audience": "client",
        "default_subject": "🎓 {{dog_name}} just graduated!",
        "default_title": "🎓 {{dog_name}} graduated!",
        "default_intro_html": "Congratulations {{first_name}}! <strong>{{dog_name}}</strong> just completed <strong>{{homework_title}}</strong>. Their certificate is attached and live in the portal.",
        "default_cta_text": "View Certificate",
        "variables": ["first_name", "client_name", "dog_name", "homework_title"],
    },
    {
        "slug": "client_day_reviewed",
        "name": "Homework Day Reviewed",
        "description": "Sent when a trainer reviews a day of homework (approve, redo, etc).",
        "category": "client",
        "audience": "client",
        "default_subject": "{{dog_name}} · Day {{day_number}} {{action_label}}",
        "default_title": "{{action_emoji}} Day {{day_number}} {{action_label}}",
        "default_intro_html": "Hi {{first_name}}, your trainer just reviewed <strong>Day {{day_number}}</strong> of <strong>{{homework_title}}</strong> for <strong>{{dog_name}}</strong>.",
        "default_cta_text": "Open Homework",
        "variables": ["first_name", "client_name", "dog_name", "homework_title", "day_number", "action_label", "action_emoji", "review_note"],
    },
    {
        "slug": "client_low_credits",
        "name": "Low Credits Warning",
        "description": "Heads-up when a credit pool drops to 2 or fewer.",
        "category": "client",
        "audience": "client",
        "default_subject": "Low {{service_label}} credits · {{remaining}} {{unit}} left",
        "default_title": "⚠️ Low {{service_label}} credits",
        "default_intro_html": "Hi {{first_name}}, heads up — you've only got <strong>{{remaining}} {{unit}}</strong> left on your <strong>{{service_label}}</strong> pack. Reach out anytime and we'll get a new pack set up so {{service_label}} doesn't pause.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "service_label", "remaining", "unit"],
    },
    {
        "slug": "client_pack_receipt",
        "name": "Credit Pack Receipt",
        "description": "Sent after a client buys a credit pack or training program.",
        "category": "client",
        "audience": "client",
        "default_subject": "Receipt · {{client_name}} · {{total_label}}",
        "default_title": "🧾 Receipt",
        "default_intro_html": "Thanks {{first_name}}! Here's your receipt for today's purchase.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "total_label", "payment_method", "sold_by", "sold_at"],
    },
    {
        "slug": "client_quote_received",
        "name": "Quote Received",
        "description": "Sent when an admin sends a quote in response to a client request.",
        "category": "client",
        "audience": "client",
        "default_subject": "Your quote from Sit Happens · {{item_name}}",
        "default_title": "💬 You have a quote",
        "default_intro_html": "Hi {{first_name}}, we just sent over a quote for <strong>{{item_name}}</strong>. Open your portal to review and book.",
        "default_cta_text": "View Quote",
        "variables": ["first_name", "client_name", "item_name", "message"],
    },
    {
        "slug": "client_dog_birthday",
        "name": "Dog Birthday",
        "description": "Automated birthday wish sent on a dog's birthday.",
        "category": "client",
        "audience": "client",
        "default_subject": "🎂 Happy birthday {{dog_name}}!",
        "default_title": "🎂 Happy birthday, {{dog_name}}!",
        "default_intro_html": "Wishing {{dog_name}} the happiest birthday from all of us at Sit Happens. Hope today is full of treats, naps, and zoomies. 🐾",
        "default_cta_text": "",
        "variables": ["first_name", "client_name", "dog_name", "age"],
    },
    {
        "slug": "client_vaccine_expiring",
        "name": "Vaccine Expiring",
        "description": "Alert when a dog's vaccine is expiring soon or expired.",
        "category": "client",
        "audience": "client",
        "default_subject": "Vaccine reminder · {{dog_name}}",
        "default_title": "💉 Vaccine reminder",
        "default_intro_html": "Hi {{first_name}}, this is a friendly reminder that <strong>{{dog_name}}</strong> has vaccines coming up. Please send us the updated paperwork when you can.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "dog_name"],
    },
    {
        "slug": "client_homework_reminder",
        "name": "Homework Reminder",
        "description": "Nudge sent if homework hasn't been logged in a while.",
        "category": "client",
        "audience": "client",
        "default_subject": "Don't forget — {{dog_name}}'s homework awaits",
        "default_title": "📋 Homework reminder",
        "default_intro_html": "Hi {{first_name}}, just a friendly nudge — <strong>{{dog_name}}</strong> has open homework waiting in the portal. Even a couple of minutes today keeps the streak alive!",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "dog_name"],
    },
    {
        "slug": "client_weekly_homework_digest",
        "name": "Weekly Homework Digest",
        "description": "Monday digest summarizing the week's homework progress.",
        "category": "client",
        "audience": "client",
        "default_subject": "Your weekly training digest · {{week_label}}",
        "default_title": "📈 Weekly progress",
        "default_intro_html": "Hi {{first_name}}, here's how your training week looks ({{week_label}}). Keep up the great work!",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "week_label"],
    },
    {
        "slug": "account_claim",
        "name": "Account Claim / Welcome",
        "description": "Sent to a client to claim their portal account or reset their password.",
        "category": "client",
        "audience": "client",
        "default_subject": "Welcome to Sit Happens · Set up your portal",
        "default_title": "👋 Welcome to Sit Happens",
        "default_intro_html": "Hi {{first_name}}, your Sit Happens portal is ready. Click below to set up your password and start tracking {{dog_name_or_dogs}} from any device.",
        "default_cta_text": "Set Up My Portal",
        "variables": ["first_name", "client_name", "dog_name_or_dogs"],
    },

    # ---------------- Admin-facing ----------------
    {
        "slug": "admin_new_booking",
        "name": "Admin · New Booking",
        "description": "Notifies the operator when a client requests a booking.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "New booking · {{dog_name}} · {{service_label}} · {{date}}",
        "default_title": "🐾 New Booking · {{dog_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> just requested a booking through the portal. It's pending your approval.",
        "default_cta_text": "Open Bookings",
        "variables": ["client_name", "dog_name", "service_label", "date", "phone", "email"],
    },
    {
        "slug": "admin_bulk_booking",
        "name": "Admin · Bulk Bookings",
        "description": "One summary email when a client creates several bookings at once.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "{{count}} new bookings · {{dog_name}} · {{kind}}",
        "default_title": "🐾 {{count}} new bookings · {{dog_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> just created <strong>{{count}}</strong> bookings via the portal ({{kind}}).",
        "default_cta_text": "Open Bookings",
        "variables": ["client_name", "dog_name", "service_label", "count", "kind", "dates_preview"],
    },
    {
        "slug": "admin_new_client",
        "name": "Admin · New Client Signup",
        "description": "Fires when a new client account is created.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "New client signup · {{client_name}}",
        "default_title": "🆕 New client · {{client_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> just created a Sit Happens portal account.",
        "default_cta_text": "Open Clients",
        "variables": ["client_name", "email", "phone"],
    },
    {
        "slug": "admin_vaccine_upload_pending",
        "name": "Admin · Vaccine Approval Waiting",
        "description": "Fires when a client uploads a vaccine record that needs review.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Vaccine approval needed · {{dog_name}} · {{vaccine}}",
        "default_title": "💉 Vaccine approval waiting",
        "default_intro_html": "<strong>{{client_name}}</strong> uploaded <strong>{{vaccine}}</strong> records for <strong>{{dog_name}}</strong>. Review and approve the upload before this vaccine unlocks booking.",
        "default_cta_text": "Open Dashboard",
        "variables": ["client_name", "dog_name", "vaccine", "expires_on"],
    },
    {
        "slug": "admin_first_booking",
        "name": "Admin · First Booking",
        "description": "Fires the first time a brand-new client books.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "🎉 First booking · {{client_name}} · {{dog_name}}",
        "default_title": "🎉 First booking from {{client_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> just made their first booking ever. Celebrate the win! 🎊",
        "default_cta_text": "Open Booking",
        "variables": ["client_name", "dog_name", "service_label", "date"],
    },
    {
        "slug": "admin_quote_request",
        "name": "Admin · Quote Requested",
        "description": "Fires when a client requests a quote for a service.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Quote request · {{item_name}} · {{client_name}}",
        "default_title": "💬 Quote request",
        "default_intro_html": "<strong>{{client_name}}</strong> is asking about <strong>{{item_name}}</strong>.",
        "default_cta_text": "Open Quotes",
        "variables": ["client_name", "item_name", "message", "phone", "email"],
    },
    {
        "slug": "client_payment_plan_created",
        "name": "Payment Plan Created",
        "description": "Sent to the client when a payment plan is set up — includes link to sign agreement.",
        "category": "client",
        "audience": "client",
        "default_subject": "Action required · Payment plan for {{program_name}}",
        "default_title": "📝 Your payment plan is ready",
        "default_intro_html": "Hi {{first_name}}, your payment plan for <strong>{{program_name}}</strong> is set up — <strong>{{installment_count}} payments of {{installment_amount}}</strong>. Please review and sign the agreement to activate.",
        "default_cta_text": "Review & Sign",
        "variables": ["first_name", "client_name", "program_name", "total_amount", "installment_count", "installment_amount", "first_due_date"],
    },
    {
        "slug": "client_payment_due_soon",
        "name": "Payment Due Soon",
        "description": "Automated reminder N days before each installment is due.",
        "category": "client",
        "audience": "client",
        "default_subject": "Reminder · {{amount}} due {{due_date}}",
        "default_title": "💳 Payment due {{due_date}}",
        "default_intro_html": "Hi {{first_name}}, this is a friendly heads-up that <strong>{{amount}}</strong> is due on <strong>{{due_date}}</strong> for your <strong>{{program_name}}</strong> payment plan.",
        "default_cta_text": "View Plan",
        "variables": ["first_name", "client_name", "program_name", "amount", "due_date", "remaining_count"],
    },
    {
        "slug": "client_payment_received",
        "name": "Payment Received",
        "description": "Confirmation when an installment is marked paid.",
        "category": "client",
        "audience": "client",
        "default_subject": "Payment received · Thanks, {{first_name}}!",
        "default_title": "✅ Payment received",
        "default_intro_html": "Thanks {{first_name}}! We logged your <strong>{{amount}}</strong> payment toward your <strong>{{program_name}}</strong> plan. {{remaining_text}}",
        "default_cta_text": "View Plan",
        "variables": ["first_name", "client_name", "program_name", "amount", "paid_method", "remaining_count", "remaining_text"],
    },
    {
        "slug": "client_payment_overdue",
        "name": "Payment Overdue",
        "description": "Sent the day after an installment was due and unpaid.",
        "category": "client",
        "audience": "client",
        "default_subject": "Past due · {{amount}} · {{program_name}}",
        "default_title": "⏰ Past due",
        "default_intro_html": "Hi {{first_name}}, the <strong>{{amount}}</strong> payment for your <strong>{{program_name}}</strong> plan was due on <strong>{{due_date}}</strong>. Please log in to your portal to settle up — or reach out if you need to adjust.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "program_name", "amount", "due_date", "days_overdue"],
    },
    {
        "slug": "admin_reschedule_request",
        "name": "Admin · Reschedule Request",
        "description": "Fires when a client requests to move a prepaid session.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Reschedule request · {{client_name}} · {{dog_name}} · {{current_date}}",
        "default_title": "🔄 Reschedule request · {{dog_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> wants to move <strong>{{dog_name}}</strong>'s prepaid session from <strong>{{current_date}}</strong>. They proposed {{proposed_count}} alternate slot{{proposed_plural}}:<br/>{{proposed_list}}",
        "default_cta_text": "Open Requests",
        "variables": ["client_name", "dog_name", "current_date", "current_time", "proposed_count", "proposed_plural", "proposed_list"],
    },
    {
        "slug": "client_reschedule_approved",
        "name": "Reschedule Approved",
        "description": "Sent to the client when their reschedule request is approved.",
        "category": "client",
        "audience": "client",
        "default_subject": "Session moved · {{dog_name}} · {{new_date}}",
        "default_title": "✅ Session moved · {{dog_name}}",
        "default_intro_html": "Good news {{first_name}} — we moved {{dog_name}}'s session to <strong>{{new_date}}</strong> at <strong>{{new_time}}</strong>. See you then!",
        "default_cta_text": "View Booking",
        "variables": ["first_name", "client_name", "dog_name", "new_date", "new_time", "original_date"],
    },
    {
        "slug": "client_reschedule_declined",
        "name": "Reschedule Declined",
        "description": "Sent to the client when none of their proposed slots work.",
        "category": "client",
        "audience": "client",
        "default_subject": "About moving {{dog_name}}'s session",
        "default_title": "📅 Let's find another time",
        "default_intro_html": "Hi {{first_name}}, none of the slots you proposed worked on our side. We'll be in touch shortly to pencil in a time that works for both of us. The original session for <strong>{{original_date}}</strong> is still on the books for now.",
        "default_cta_text": "",
        "variables": ["first_name", "client_name", "dog_name", "original_date", "decline_reason"],
    },
    {
        "slug": "admin_training_log",
        "name": "Admin · Training Log",
        "description": "Fires when a client adds a training note to a dog.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Training note · {{dog_name}} · {{client_name}}",
        "default_title": "📝 New training note · {{dog_name}}",
        "default_intro_html": "<strong>{{client_name}}</strong> just added a training note for <strong>{{dog_name}}</strong>.",
        "default_cta_text": "Open Pipeline",
        "variables": ["client_name", "dog_name", "date"],
    },
    {
        "slug": "admin_homework_section_log",
        "name": "Admin · Homework Section Logged",
        "description": "Fires when a client logs a homework section (if per-step is enabled).",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Homework log · {{dog_name}} · {{homework_title}}",
        "default_title": "📋 Homework section logged",
        "default_intro_html": "<strong>{{client_name}}</strong> logged a section of <strong>{{homework_title}}</strong> for <strong>{{dog_name}}</strong>.",
        "default_cta_text": "Open Homework",
        "variables": ["client_name", "dog_name", "homework_title"],
    },
    {
        "slug": "admin_homework_completed",
        "name": "Admin · Homework Completed",
        "description": "Fires when a client marks a homework plan complete.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "Homework completed · {{dog_name}} · {{homework_title}}",
        "default_title": "✅ Homework complete",
        "default_intro_html": "<strong>{{client_name}}</strong> just marked <strong>{{homework_title}}</strong> complete for <strong>{{dog_name}}</strong>.",
        "default_cta_text": "Open Homework",
        "variables": ["client_name", "dog_name", "homework_title"],
    },
    {
        "slug": "admin_pl_report",
        "name": "Admin · P&L Report",
        "description": "Periodic P&L report digest sent to the owner.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "P&L report · {{period_label}}",
        "default_title": "📊 P&L Report",
        "default_intro_html": "Here's your latest profit & loss snapshot for <strong>{{period_label}}</strong>.",
        "default_cta_text": "",
        "variables": ["period_label", "revenue", "expenses", "net"],
    },
    {
        "slug": "client_report_card",
        "name": "Day-in-Pictures Report Card",
        "description": "Sent automatically when a boarding/daycare visit checks out — includes the report card photos, mood, note, plus the day's care log (meals, meds w/ photo proof, bathroom counters).",
        "category": "client",
        "audience": "client",
        "default_subject": "{{dog_name}}'s day at {{brand_name}} 📸",
        "default_title": "📸 {{dog_name}}'s day in pictures",
        "default_intro_html": "Hi {{first_name}} — here's how <strong>{{dog_name}}</strong>'s {{service_label}} went on <strong>{{visit_date}}</strong>. Thanks for trusting us with the best part of your day.",
        "default_cta_text": "View in portal",
        "variables": ["first_name", "client_name", "dog_name", "service_label", "visit_date", "brand_name"],
    },
    {
        "slug": "client_referral_payout",
        "name": "Referral Payout (to referrer)",
        "description": "Sent to the referrer when their friend completes their first appointment. Awards one free daycare day credit.",
        "category": "client",
        "audience": "client",
        "default_subject": "🎉 You just earned a free daycare day, {{first_name}}!",
        "default_title": "🎁 Your referral paid off!",
        "default_intro_html": "Hi {{first_name}} — your friend <strong>{{referred_name}}</strong> just wrapped up their first visit at {{brand_name}}. Because they used your referral code <strong>{{referral_code}}</strong>, you've earned <strong>one free daycare day</strong> on the house. Your new daycare credit balance is <strong>{{new_balance}}</strong>. Thanks for spreading the word! 🐾",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "referred_name", "referral_code", "new_balance", "brand_name"],
    },
    {
        "slug": "client_referral_welcome",
        "name": "Referral Welcome (to referee)",
        "description": "Sent to the new client when their first appointment completes, thanking them for joining via a referral and letting them know their referrer was rewarded.",
        "category": "client",
        "audience": "client",
        "default_subject": "Welcome to {{brand_name}}, {{first_name}}! 🐾",
        "default_title": "💚 Welcome to the pack",
        "default_intro_html": "Hi {{first_name}} — so glad we got to meet {{dog_name}} today! Because you joined through <strong>{{referrer_name}}</strong>'s referral, they just earned a free daycare day on us. Now it's your turn — share <strong>{{referral_code}}</strong> with another dog parent and you'll earn one too when they finish their first visit.",
        "default_cta_text": "Open Portal",
        "variables": ["first_name", "client_name", "dog_name", "referrer_name", "referral_code", "brand_name"],
    },
    {
        "slug": "admin_trivia_milestone",
        "name": "Admin · Trivia Milestone Earned",
        "description": "Notifies the operator when a client hits a trivia streak reward (puzzle toy / retail credit / service upgrade) so the perk can be handed over at next pickup.",
        "category": "admin",
        "audience": "admin",
        "default_subject": "🏆 Trivia perk earned · {{client_name}} · {{days}}-day streak",
        "default_title": "🏆 Trivia milestone earned",
        "default_intro_html": "<strong>{{client_name}}</strong> just hit a <strong>{{days}}-day trivia streak</strong> and earned a perk: <em>{{reward_label}}</em>. Drop it on them at their next pickup!",
        "default_cta_text": "Open Client",
        "variables": ["client_name", "days", "reward_label", "perk_type", "earned_on"],
    },
    {
        "slug": "client_partial_payment_receipt",
        "name": "Partial Payment Receipt",
        "description": "Auto-sent on partial checkout payment — confirms what was paid and the remaining balance on the tab.",
        "category": "client",
        "audience": "client",
        "default_subject": "Payment received · balance remaining",
        "default_title": "💳 Payment received",
        # NOTE: intro is built dynamically per-payment by the handler — keep
        # this empty so the runtime fallback_intro is actually rendered.
        "default_intro_html": "",
        "variables": ["first_name", "dog_name"],
    },
    {
        "slug": "client_tab_payment_receipt",
        "name": "Tab Payment Receipt",
        "description": "Auto-sent when a payment is applied directly to a client's running tab (not tied to a specific booking).",
        "category": "client",
        "audience": "client",
        "default_subject": "Payment received · thanks!",
        "default_title": "💳 Payment received",
        # Intro built dynamically per-payment — keep blank.
        "default_intro_html": "",
        "variables": ["first_name"],
    },
    {
        "slug": "client_account_statement",
        "name": "Account Statement",
        "description": "Full ledger statement emailed to a client on demand — shows every charge, payment, and adjustment plus the current balance and how to settle up.",
        "category": "client",
        "audience": "client",
        "default_subject": "Your account statement",
        "default_title": "🧾 Your account statement",
        # Intro carries the entire styled balance card + ledger TABLE built
        # at send time — MUST stay empty so the runtime fallback wins.
        "default_intro_html": "",
        "variables": ["first_name", "brand_name"],
    },
]


def get_template(slug: str):
    """Return the registry entry for `slug`, or None if not registered."""
    for t in EMAIL_TEMPLATES:
        if t["slug"] == slug:
            return t
    return None


def list_templates():
    """Return all registered templates."""
    return list(EMAIL_TEMPLATES)
