"""Default trophy catalog. Seeded on first boot; admins can edit/create custom
trophies via the /api/trophies endpoints. Each entry's `code` is the stable
slug used for idempotent awarding."""

# Tier visual styling — used by frontend AND share-card renderer.
TIER_COLORS = {
    "bronze":   {"ring": "#cd7f32", "fill": "#3a2412", "label": "#f0c89c"},
    "silver":   {"ring": "#bfc7cf", "fill": "#1e2a33", "label": "#dde6ee"},
    "gold":     {"ring": "#f5c037", "fill": "#3a2a08", "label": "#ffe7a3"},
    "platinum": {"ring": "#7ee0ff", "fill": "#0c2a36", "label": "#bff0ff"},
}

# trigger_type:
#   auto = evaluator runs after the relevant write hook fires
#   manual = admin-only, only awarded via the manual award endpoint
# trigger_kind (for auto):
#   goal_score_5_count    -> threshold = N goals at score 5 in any program
#   program_completed     -> threshold = N programs completed
#   homework_streak_days  -> threshold = N consecutive days with >=1 homework completed
#   homework_completed    -> threshold = N total homework completed by this client
#   visit_count           -> threshold = N total checkouts across all dogs of this client
#   successful_referrals  -> threshold = N referrals collection rows where this client is referrer
SEED_TROPHIES = [
    # --- DOG TROPHIES ---
    {
        "code": "dog_quick_learner",
        "name": "Quick Learner",
        "description": "First training goal mastered with a perfect 5 rating.",
        "category": "dog",
        "tier": "bronze",
        "icon": "fa-bolt",
        "trigger_type": "auto",
        "trigger_kind": "goal_score_5_count",
        "threshold": 1,
        "active": True,
        "is_default": True,
    },
    {
        "code": "dog_skill_master",
        "name": "Skill Master",
        "description": "Five training goals mastered. This pup means business.",
        "category": "dog",
        "tier": "silver",
        "icon": "fa-medal",
        "trigger_type": "auto",
        "trigger_kind": "goal_score_5_count",
        "threshold": 5,
        "active": True,
        "is_default": True,
    },
    {
        "code": "dog_top_dog",
        "name": "Top Dog",
        "description": "Ten training goals mastered. Top of the class!",
        "category": "dog",
        "tier": "gold",
        "icon": "fa-crown",
        "trigger_type": "auto",
        "trigger_kind": "goal_score_5_count",
        "threshold": 10,
        "active": True,
        "is_default": True,
    },
    {
        "code": "dog_graduate",
        "name": "Sit Happens Graduate",
        "description": "Successfully completed a full training program.",
        "category": "dog",
        "tier": "platinum",
        "icon": "fa-graduation-cap",
        "trigger_type": "auto",
        "trigger_kind": "program_completed",
        "threshold": 1,
        "active": True,
        "is_default": True,
    },
    {
        "code": "dog_star_of_day",
        "name": "Star of the Day",
        "description": "Earned a Star of the Day report card.",
        "category": "dog",
        "tier": "gold",
        "icon": "fa-star",
        "trigger_type": "manual",
        "threshold": 0,
        "active": True,
        "is_default": True,
    },
    {
        "code": "dog_birthday",
        "name": "Birthday Pup",
        "description": "Celebrated their birthday at Sit Happens!",
        "category": "dog",
        "tier": "silver",
        "icon": "fa-cake-candles",
        "trigger_type": "manual",
        "threshold": 0,
        "active": True,
        "is_default": True,
    },
    # --- CLIENT TROPHIES ---
    {
        "code": "client_homework_hero",
        "name": "Homework Hero",
        "description": "Completed homework seven days in a row.",
        "category": "client",
        "tier": "bronze",
        "icon": "fa-fire",
        "trigger_type": "auto",
        "trigger_kind": "homework_streak_days",
        "threshold": 7,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_dedicated",
        "name": "Dedicated Owner",
        "description": "Logged 25 completed homework assignments.",
        "category": "client",
        "tier": "silver",
        "icon": "fa-book-open",
        "trigger_type": "auto",
        "trigger_kind": "homework_completed",
        "threshold": 25,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_coach_of_year",
        "name": "Coach of the Year",
        "description": "An incredible 100 completed homework assignments!",
        "category": "client",
        "tier": "gold",
        "icon": "fa-whistle",  # falls back to chalkboard-teacher if not present
        "trigger_type": "auto",
        "trigger_kind": "homework_completed",
        "threshold": 100,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_regular",
        "name": "Regular",
        "description": "Ten visits to Sit Happens.",
        "category": "client",
        "tier": "bronze",
        "icon": "fa-paw",
        "trigger_type": "auto",
        "trigger_kind": "visit_count",
        "threshold": 10,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_loyal",
        "name": "Loyal Pack Member",
        "description": "Fifty visits! You're family now.",
        "category": "client",
        "tier": "silver",
        "icon": "fa-heart",
        "trigger_type": "auto",
        "trigger_kind": "visit_count",
        "threshold": 50,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_legend",
        "name": "Sit Happens Legend",
        "description": "One hundred visits. Hall of Fame status.",
        "category": "client",
        "tier": "gold",
        "icon": "fa-trophy",
        "trigger_type": "auto",
        "trigger_kind": "visit_count",
        "threshold": 100,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_friend_bringer",
        "name": "Friend Bringer",
        "description": "Your first referral completed their first appointment!",
        "category": "client",
        "tier": "bronze",
        "icon": "fa-user-plus",
        "trigger_type": "auto",
        "trigger_kind": "successful_referrals",
        "threshold": 1,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_pack_builder",
        "name": "Pack Builder",
        "description": "Three referrals who became Sit Happens regulars.",
        "category": "client",
        "tier": "silver",
        "icon": "fa-people-group",
        "trigger_type": "auto",
        "trigger_kind": "successful_referrals",
        "threshold": 3,
        "active": True,
        "is_default": True,
    },
    {
        "code": "client_ambassador",
        "name": "Ambassador",
        "description": "Ten successful referrals. You ARE Sit Happens.",
        "category": "client",
        "tier": "gold",
        "icon": "fa-bullhorn",
        "trigger_type": "auto",
        "trigger_kind": "successful_referrals",
        "threshold": 10,
        "active": True,
        "is_default": True,
    },
]
