import { useCallback, useEffect, useState } from "react";
import { api } from "../../../lib/api";

const readAsDataUrl = (file) => new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(r.result); r.onerror = reject; r.readAsDataURL(file); });


const supportRemaining = (home, workspace, kind) => {
  const key = kind === "checkpoint" ? "checkpoint" : "assist";
  const live = home?.support?.[`${key}_remaining`];
  if (live !== undefined) return live;
  const wsRemaining = workspace?.support?.[`${key}_remaining`];
  if (wsRemaining !== undefined) return wsRemaining;
  return workspace?.support?.[`${key}_allowance`] ?? null;
};

function TrainerSupportSummary({ home, workspace }) {
  const checkpoints = supportRemaining(home, workspace, "checkpoint");
  const assists = supportRemaining(home, workspace, "assist");
  return <div className="rounded-xl border border-shBorder bg-black/10 p-3 text-[11px] text-shTextMuted" data-testid="school-trainer-support-summary">
    <i className="fas fa-handshake-angle text-shSecondary mr-2"/><b className="text-shText">Trainer support:</b>{" "}
    {checkpoints == null ? "Trainer-reviewed checkpoints at required course milestones" : `${checkpoints} checkpoint review${Number(checkpoints) === 1 ? "" : "s"} remaining`}
    {" · "}
    {assists == null ? "Trainer Assist available when direct help is needed" : `${assists} Trainer Assist${Number(assists) === 1 ? "" : "s"} remaining`}
    {workspace?.access_expires_at && <span className="block mt-1"><i className="fas fa-calendar-xmark mr-1"/>Access through {new Date(workspace.access_expires_at).toLocaleDateString()}</span>}
  </div>;
}

export default function StudentWorkspaceExtras({ enrollmentId, home, mode = "home", onChanged, onOpenLesson, onOpenHomework }) {
  const [workspace, setWorkspace] = useState(null); const [requests, setRequests] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async()=>{if(!enrollmentId)return;const [w,r]=await Promise.all([api.get(`/portal/school/${enrollmentId}/workspace`),api.get(`/portal/school/${enrollmentId}/requests`)]);setWorkspace(w.data||{});setRequests(r.data||[]);},[enrollmentId]);
  useEffect(()=>{setWorkspace(null);load().catch(()=>setWorkspace({}));},[load]);
  const baseline = home?.onboarding?.baseline || workspace?.baseline;
  const needsOnboarding = home?.current_action?.type === "onboarding" || (home?.onboarding?.config?.enabled && home?.onboarding?.config?.require_baseline && !baseline);
  if (!workspace && !needsOnboarding) return null;
  const plans=(workspace?.training_plans||[]).filter(p=>p.status==='active'); const openRequests=requests.filter(r=>r.status==='open');
  return <div className="space-y-4" data-testid="student-workspace-extras">
    {needsOnboarding && <Onboarding enrollmentId={enrollmentId} initial={baseline} config={home?.onboarding?.config || {}} onDone={async()=>{await load();onChanged?.();}}/>}
    {!needsOnboarding && plans.length>0 && <section className="rounded-2xl border border-shPrimary/25 bg-shPrimary/[0.04] p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-shPrimary">Trainer-prescribed plan</p><h3 className="text-lg font-black text-shText mt-1">{plans[0].title}</h3></div><span className="text-[10px] text-shTextMuted">{plans[0].starts_on||''}</span></div>{plans[0].summary&&<p className="text-[13px] text-shTextMuted mt-2">{plans[0].summary}</p>}<div className="space-y-2 mt-4">{(plans[0].tasks||[]).map(t=><PlanTask key={t.id} enrollmentId={enrollmentId} planId={plans[0].id} task={t} onDone={load} onOpenLesson={onOpenLesson} onOpenHomework={onOpenHomework}/>)}</div></section>}
    {!needsOnboarding && openRequests.length>0 && <section className="space-y-2"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-shAccent">Your trainer is asking for an update</p><p className="text-[12px] text-shTextMuted mt-1">Complete these requests so your trainer can see how training is going.</p></div>{openRequests.map(r=><TrainerRequest key={r.id} request={r} enrollmentId={enrollmentId} onDone={async()=>{await load();onChanged?.();}}/>)}</section>}
    {mode==='home' && !needsOnboarding && (home?.support || workspace?.support) && <TrainerSupportSummary home={home} workspace={workspace}/>}
  </div>;
}

function Onboarding({enrollmentId,initial,config,onDone}){const [form,setForm]=useState(initial||{goals:'',current_challenges:'',training_experience:'',equipment:'',preferred_schedule:'',baseline_note:''});const [busy,setBusy]=useState(false);const equipmentRequired=!!config?.require_equipment_check;const save=async()=>{if(equipmentRequired&&!String(form.equipment||'').trim())return;setBusy(true);try{await api.post(`/portal/school/${enrollmentId}/baseline`,form);onDone?.();}finally{setBusy(false)}};return <section className="rounded-3xl border border-shSecondary/35 bg-gradient-to-br from-shSecondary/[0.09] to-black/10 p-5 sm:p-6" data-testid="school-onboarding"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-shSecondary">Before training starts</p><h2 className="text-xl sm:text-2xl font-black text-shText mt-1">Help your trainer understand where you're starting</h2><p className="text-[13px] text-shTextMuted mt-2">This becomes the baseline for your dog's training record and helps us give better feedback.</p><div className="grid sm:grid-cols-2 gap-3 mt-5">{[['goals','What do you want to accomplish?'],['current_challenges','What is hardest right now?'],['training_experience','What training have you already done?'],['equipment',`What equipment do you currently use?${equipmentRequired?' *':''}`],['preferred_schedule','When can you realistically practice?'],['baseline_note','Anything else your trainer should know?']].map(([k,l])=><label key={k} className="block"><span className="text-[10px] font-black uppercase tracking-widest text-shTextMuted">{l}</span><textarea value={form[k]||''} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))} className="mt-1 w-full min-h-[82px] rounded-xl border border-shBorder bg-black/20 p-3 text-[13px] text-shText"/></label>)}</div><button onClick={save} disabled={busy||(equipmentRequired&&!String(form.equipment||'').trim())} className="mt-4 w-full sm:w-auto min-h-[48px] px-5 rounded-xl bg-shPrimary text-bgHeader text-[12px] font-black uppercase tracking-widest disabled:opacity-50">Save & Start School</button></section>}

function PlanTask({enrollmentId,planId,task,onDone,onOpenLesson,onOpenHomework}){const [busy,setBusy]=useState(false);const complete=async()=>{setBusy(true);try{await api.post(`/portal/school/${enrollmentId}/plans/${planId}/tasks/${task.id}/complete`);await onDone?.();}finally{setBusy(false)}};return <div className={`rounded-xl border p-3 ${task.completed_at?'border-shPrimary/20 bg-shPrimary/[0.04]':'border-shBorder bg-black/15'}`}><div className="flex items-start gap-3"><button disabled={!!task.completed_at||busy} onClick={complete} className={`w-8 h-8 rounded-full border shrink-0 ${task.completed_at?'border-shPrimary bg-shPrimary text-bgHeader':'border-shBorder text-shTextMuted'}`}><i className={`fas ${task.completed_at?'fa-check':'fa-circle'}`}/></button><div className="min-w-0 flex-1"><p className="font-black text-[13px] text-shText">{task.title}</p>{task.instructions&&<p className="text-[12px] text-shTextMuted mt-1 whitespace-pre-wrap">{task.instructions}</p>}<div className="flex flex-wrap gap-2 mt-2">{task.estimated_minutes!=null&&<span className="text-[10px] text-shTextMuted"><i className="fas fa-clock mr-1"/>{task.estimated_minutes} min</span>}{task.lesson_id&&<button onClick={()=>onOpenLesson?.(task.lesson_id)} className="text-[10px] font-black text-shSecondary uppercase">Open lesson</button>}{task.homework_id&&<button onClick={()=>onOpenHomework?.(task.homework_id)} className="text-[10px] font-black text-shPrimary uppercase">Open practice</button>}</div></div></div></div>}

function TrainerRequest({request,enrollmentId,onDone}){const [note,setNote]=useState('');const [file,setFile]=useState(null);const [busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{let media_id=null;if(file){const data=await readAsDataUrl(file);const up=await api.post(`/portal/school/${enrollmentId}/requests/${request.id}/media`,{data,filename:file.name});media_id=up.data.media_id;}await api.post(`/portal/school/${enrollmentId}/requests/${request.id}/respond`,{note,media_id});onDone?.();}finally{setBusy(false)}};return <div className="rounded-2xl border border-shAccent/25 bg-shAccent/[0.035] p-4"><div className="flex justify-between gap-2"><div><p className="text-[10px] font-black uppercase tracking-widest text-shAccent">{request.type.replace(/_/g,' ')}</p><h3 className="font-black text-shText mt-1">{request.title}</h3></div>{request.due_at&&<span className="text-[10px] text-shTextMuted">Due {new Date(request.due_at).toLocaleDateString()}</span>}</div>{request.instructions&&<p className="text-[13px] text-shTextMuted mt-2">{request.instructions}</p>}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note for your trainer…" className="w-full min-h-[70px] mt-3 rounded-xl border border-shBorder bg-black/20 p-3 text-[12px] text-shText"/>{request.type==='video'&&<label className="mt-2 block rounded-xl border border-dashed border-shBorder p-3 text-[11px] text-shTextMuted cursor-pointer"><i className="fas fa-video mr-2 text-shSecondary"/>{file?file.name:'Choose a training video'}<input type="file" accept="video/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}<button disabled={busy||(!note.trim()&&!file)} onClick={submit} className="mt-3 min-h-[42px] px-4 rounded-xl bg-shPrimary text-bgHeader text-[11px] font-black uppercase tracking-widest disabled:opacity-40">Send to trainer</button></div>}
