import { useEffect, useState } from "react";
import { api } from "../../lib/api";
function Card({label,value,detail}){return <div className="rounded-2xl border border-shBorder bg-[var(--sh-card-base)] p-4"><p className="text-[10px] uppercase tracking-widest font-black text-shTextMuted">{label}</p><p className="text-3xl font-black text-shText mt-1">{value ?? "—"}</p>{detail&&<p className="text-xs text-shTextMuted mt-1">{detail}</p>}</div>}
export default function SchoolAnalyticsPanel(){
  const [d,setD]=useState(null);
  useEffect(()=>{api.get('/admin/school/analytics').then(r=>setD(r.data)).catch(()=>setD({error:true}))},[]);
  if(!d)return <div className="h-56 rounded-2xl bg-shBorder/20 animate-pulse"/>;
  if(d.error)return <p className="text-shAccent">Could not load School analytics.</p>;
  return <div className="space-y-5" data-testid="school-analytics">
    <div className="grid grid-cols-2 xl:grid-cols-6 gap-3">
      <Card label="Students" value={d.students?.total}/><Card label="Active" value={d.students?.active}/><Card label="Completed" value={d.students?.completed}/><Card label="Completion rate" value={`${d.students?.completion_rate||0}%`}/><Card label="Inactive" value={d.students?.inactive||0} detail="Past intervention threshold"/><Card label="Avg. completion" value={d.students?.avg_completion_days!=null?`${d.students.avg_completion_days}d`:'—'}/>
    </div>
    <div className="grid md:grid-cols-3 gap-4">
      <section className="rounded-2xl border border-shBorder p-4 md:col-span-2"><h3 className="font-black text-shText">Checkpoint performance</h3><div className="grid grid-cols-2 lg:grid-cols-4 gap-2 mt-3"><Card label="Reviews" value={d.checkpoints?.graded}/><Card label="First-pass rate" value={`${d.checkpoints?.first_pass_rate||0}%`}/><Card label="Remediation" value={d.checkpoints?.remediation}/><Card label="Trainer Assist" value={d.checkpoints?.trainer_assist}/></div><p className="text-xs text-shTextMuted mt-3">Average trainer review time: <b className="text-shText">{d.checkpoints?.avg_review_hours!=null?`${d.checkpoints.avg_review_hours}h`:'No data yet'}</b></p></section>
      <section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Student support</h3><p className="text-3xl font-black text-shSecondary mt-4">{d.communication?.avg_first_response_hours!=null?`${d.communication.avg_first_response_hours}h`:'—'}</p><p className="text-xs text-shTextMuted">Average first response</p><p className="text-xs text-shTextMuted mt-4">Open attention items: <b className="text-shText">{d.engagement?.open_attention||0}</b></p><p className="text-xs text-shTextMuted mt-1">Conversation threads: <b className="text-shText">{d.communication?.threads||0}</b></p></section>
    </div>
    <section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Training engagement</h3><div className="grid sm:grid-cols-2 gap-3 mt-3"><Card label="Practice sessions · 30 days" value={d.engagement?.practice_sessions_30d||0}/><Card label="Practice / active student" value={d.engagement?.practice_per_active_student_30d||0} detail="Last 30 days"/></div></section>
    {(d.courses||[]).length>0&&<section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Course performance</h3><div className="overflow-x-auto mt-3"><table className="w-full min-w-[680px] text-xs"><thead><tr className="text-shTextMuted text-left"><th className="py-2">Course</th><th>Students</th><th>Active</th><th>Complete</th><th>Completion</th><th>Avg. days</th></tr></thead><tbody>{d.courses.map(c=><tr key={c.program_name} className="border-t border-shBorder/50"><td className="py-2.5 font-bold text-shText">{c.program_name}</td><td>{c.students}</td><td>{c.active}</td><td>{c.completed}</td><td className="text-shPrimary font-black">{c.completion_rate}%</td><td>{c.avg_completion_days??'—'}</td></tr>)}</tbody></table></div></section>}
    {(d.dropoff_lessons||[]).length>0&&<section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Where active students are sitting</h3><p className="text-xs text-shTextMuted mt-1">Useful for spotting lessons where progress tends to stall.</p><div className="grid md:grid-cols-2 gap-2 mt-3">{d.dropoff_lessons.slice(0,8).map((x,i)=><div key={`${x.program_name}-${x.lesson_name}-${i}`} className="rounded-xl bg-black/15 p-3 flex items-center gap-3"><div className="text-2xl font-black text-shSecondary">{x.active_students}</div><div><p className="text-sm font-black text-shText">{x.lesson_name||x.module_name||'Current step'}</p><p className="text-[10px] text-shTextMuted">{x.program_name}{x.module_name?` · ${x.module_name}`:''}</p></div></div>)}</div></section>}
    {(d.friction_lessons||[]).length>0&&<section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Where students need the most help</h3><p className="text-xs text-shTextMuted mt-1">Questions, stuck reports, and repeated difficulty — useful for improving the curriculum.</p><div className="grid md:grid-cols-2 gap-2 mt-3">{d.friction_lessons.slice(0,8).map((f,i)=><div key={`${f.program_name}-${f.lesson_name}-${i}`} className="rounded-xl bg-black/15 p-3"><p className="text-sm font-black text-shText">{f.lesson_name}</p><p className="text-[10px] text-shTextMuted">{f.program_name}</p><p className="text-[11px] text-shTextMuted mt-2">{f.questions} questions · {f.stuck} stuck · {f.difficulty} difficult</p></div>)}</div></section>}
    {(d.trainer_workload||[]).length>0&&<section className="rounded-2xl border border-shBorder p-4"><h3 className="font-black text-shText">Trainer workload</h3><div className="flex flex-wrap gap-2 mt-3">{d.trainer_workload.map(t=><span key={t.trainer_id||'none'} className="rounded-xl bg-black/15 px-3 py-2 text-xs text-shText"><b>{t.name}</b> · {t.active_students} active</span>)}</div></section>}
  </div>
}
